# ~/.config/fuzzel/fuzzel.ini

[main]
font=Maple Mono:size=12
dpi-aware=no
terminal=ghostty -e
prompt="  "
icon-theme=Hatter-Red
icons-enabled=yes
lines=10
width=38
horizontal-pad=18
vertical-pad=14
inner-pad=8
line-height=22
layer=overlay
exit-on-keyboard-focus-loss=yes

[colors]
background=0c0808e0
text=f5ead0ff
prompt=7a4a44ff
placeholder=7a4a44ff
input=f5ead0ff
match=c9242bff
selection=c9242b38
selection-text=ffffffff
selection-match=c9242bff
counter=7a4a44ff
border=c9242b4d

[border]
width=1
radius=10

[dmenu]
exit-immediately-if-empty=yes

[key-bindings]
cancel=Escape Control+c
execute=Return KP_Enter Control+y
prev=Up Control+p
next=Down Control+n
